
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN GREATER ID INCREMENT LBRACE LPAREN NUMBER PAN PARAQUE RBRACE RPAREN SEMIprogram : PARAQUE LPAREN declaration SEMI condition SEMI increment SEMI RPAREN LBRACE ID RBRACEdeclaration : PAN ID ASSIGN NUMBERcondition : ID GREATER NUMBERincrement : ID INCREMENT'
    
_lr_action_items = {'PARAQUE':([0,],[2,]),'$end':([1,22,],[0,-1,]),'LPAREN':([2,],[3,]),'PAN':([3,],[5,]),'SEMI':([4,8,13,14,16,18,],[6,11,-2,17,-3,-4,]),'ID':([5,6,11,20,],[7,9,15,21,]),'ASSIGN':([7,],[10,]),'GREATER':([9,],[12,]),'NUMBER':([10,12,],[13,16,]),'INCREMENT':([15,],[18,]),'RPAREN':([17,],[19,]),'LBRACE':([19,],[20,]),'RBRACE':([21,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declaration':([3,],[4,]),'condition':([6,],[8,]),'increment':([11,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PARAQUE LPAREN declaration SEMI condition SEMI increment SEMI RPAREN LBRACE ID RBRACE','program',12,'p_program','loca.py',53),
  ('declaration -> PAN ID ASSIGN NUMBER','declaration',4,'p_declaration','loca.py',55),
  ('condition -> ID GREATER NUMBER','condition',3,'p_condition','loca.py',58),
  ('increment -> ID INCREMENT','increment',2,'p_increment','loca.py',61),
]
